services:
  fastapi:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back/src:/back
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:8000/api/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 3s

  react:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/front:cached
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 3s
    depends_on:
      fastapi:
        condition: service_healthy

  nginx:
    image: nginx:1.27.1
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 3s
    volumes:
      - ./docker/nginx/config/dev_default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      react:
        condition: service_healthy

  tunnel:
    restart: always
    image: cloudflare/cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiZTEzYzBlNTgwMjVjZThiNWMzMWI0Y2E4Mjg4MzM2YjgiLCJ0IjoiZTY3MjUwNmEtYjQyMC00MjM5LTkxNDItMzE2ODg3ZGVlZGQ2IiwicyI6IllXWmhabVkwTWpZdE1ERXhNQzAwTUdNekxUaGhOREF0WVdNMU5URTFOVFUzWWpWbSJ9
    depends_on:
      nginx:
        condition: service_healthy