services:
  fastapi:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  react:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
